# Generated by Django 5.2 on 2026-01-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_display', '0003_transaksi_detailtransaksi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailtransaksi',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='transaksi',
            table='transaksi',
        ),
    ]
