# Generated by Django 5.2 on 2026-01-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_display', '0004_alter_detailtransaksi_options_alter_transaksi_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detailtransaksi',
            table='detail_transaksi',
        ),
    ]
